# Generated by Django 5.1.6 on 2025-03-16 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_signupngo_account_number_signupngo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
