# Generated by Django 5.1.6 on 2025-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_volunteer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name': 'NGO', 'verbose_name_plural': 'NGOs'},
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='documents',
        ),
        migrations.AddField(
            model_name='ngo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_certificates/'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
