# Generated by Django 5.1.5 on 2025-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ngo_options_remove_ngo_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisteredNGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('animal', 'Animal Welfare'), ('food', 'Food'), ('shelter', 'Shelter'), ('others', 'Others')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ngo',
            name='services',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('animal', 'Animal Welfare'), ('food', 'Food'), ('shelter', 'Shelter'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signupngo',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('animal', 'Animal Welfare'), ('food', 'Food'), ('shelter', 'Shelter'), ('others', 'Others')], max_length=20),
        ),
    ]
