# Generated by Django 5.0.3 on 2025-03-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_preregisteredngo_alter_ngo_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupngo',
            name='additional_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_certificates/', verbose_name='Additional Required Certificate'),
        ),
    ]
