# Generated by Django 5.1.6 on 2025-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_signupngo_additional_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='ngo_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_certificates/'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='ngo_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='ngo_profile_images/'),
        ),
        migrations.AddField(
            model_name='signupngo',
            name='ngo_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_certificates/'),
        ),
        migrations.AddField(
            model_name='signupngo',
            name='ngo_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='ngo_profile_images/'),
        ),
        migrations.AlterField(
            model_name='signupngo',
            name='additional_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_certificates/'),
        ),
    ]
