# Generated by Django 5.1.6 on 2025-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_old_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill_photo',
            field=models.ImageField(blank=True, null=True, upload_to='expense/bills/'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo/certificates/', verbose_name='NGO Certificate'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='ngo/profile/images/', verbose_name='NGO Profile Image'),
        ),
        migrations.AlterField(
            model_name='signupngo',
            name='ngo_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo/certificates/', verbose_name='NGO Certificate'),
        ),
        migrations.AlterField(
            model_name='signupngo',
            name='ngo_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='ngo/profile/images/', verbose_name='NGO Profile Image'),
        ),
    ]
